version: '3'

services:
  zookeeper-1:
    hostname: zookeeper-1
    image: zookeeper:3.6
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2128
      ZOO_SERVERS: server.1=zookeeper-1:22888:23888;2181 server.2=zookeeper-2:32888:33888;2181 server.3=zookeeper-3:42888:43888;2181
    ports:
      - 22181:2181
      - 22888:22888
      - 23888:23888
    volumes:
      - ./data/zookeeper-1/data:/data
      - ./data/zookeeper-1/datalog:/datalog
      - ./data/zookeeper-1/logs:/logs

  zookeeper-2:
    hostname: zookeeper-2
    image: zookeeper:3.6
    environment:
      ZOO_MY_ID: 2
      ZOO_PORT: 2128
      ZOO_SERVERS: server.1=zookeeper-1:22888:23888;2181 server.2=zookeeper-2:32888:33888;2181 server.3=zookeeper-3:42888:43888;2181
    ports:
      - 32181:2181
      - 32888:32888
      - 33888:33888
    volumes:
      - ./data/zookeeper-2/data:/data
      - ./data/zookeeper-2/datalog:/datalog
      - ./data/zookeeper-2/logs:/logs

  zookeeper-3:
    hostname: zookeeper-3
    image: zookeeper:3.6
    environment:
      ZOO_MY_ID: 3
      ZOO_PORT: 2128
      ZOO_SERVERS: server.1=zookeeper-1:22888:23888;2181 server.2=zookeeper-2:32888:33888;2181 server.3=zookeeper-3:42888:43888;2181
    ports:
      - 42181:2181
      - 42888:42888
      - 43888:43888
    volumes:
      - ./data/zookeeper-3/data:/data
      - ./data/zookeeper-3/datalog:/datalog
      - ./data/zookeeper-3/logs:/logs

  zookeeper-navigator:
    hostname: zookeeper-navigator
    container_name: zookeeper-navigator
    image: elkozmon/zoonavigator:1.1.2
    restart: always
    ports:
      - 8095:9000
    environment:
      HTTP_PORT: 9000
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  kafka-1:
    image: confluentinc/cp-kafka:7.1.0
    hostname: kafka-1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 19092:19092
      - 19094:19094
      - 19095:19095
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_LISTENERS: INTERNAL://:19092,EXTERNAL://:19094,EXTERNAL2://:19095
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://172.31.47.65:19094,EXTERNAL2://fallrays.com:19095
      KAFKA_ADVERTISED_HOST_NAME: fallrays.com
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,EXTERNAL2:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      BOOTSTRAP_SERVERS: kafka-1:19092,kafka-2:29092,kafka-3:39092
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '2'
      KAFKA_NUM_PARTITIONS: '2'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
    volumes:
      - ./data/kafka-1/data:/var/lib/kafka/data
      - ./data/kafka-1/secrets:/etc/kafka/secrets

  kafka-2:
    image: confluentinc/cp-kafka:7.1.0
    hostname: kafka-2
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 29092:29092
      - 29094:29094
      - 29095:29095
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:29094,EXTERNAL2://:29095
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29092,EXTERNAL://172.31.47.65:29094,EXTERNAL2://fallrays.com:29095
      KAFKA_ADVERTISED_HOST_NAME: fallrays.com
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,EXTERNAL2:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      BOOTSTRAP_SERVERS: kafka-1:19092,kafka-2:29092,kafka-3:39092
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '2'
      KAFKA_NUM_PARTITIONS: '2'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
    volumes:
      - ./data/kafka-2/data:/var/lib/kafka/data
      - ./data/kafka-2/secrets:/etc/kafka/secrets

  kafka-3:
    image: confluentinc/cp-kafka:7.1.0
    hostname: kafka-3
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 39092:39092
      - 39094:39094
      - 39095:39095
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_LISTENERS: INTERNAL://:39092,EXTERNAL://:39094,EXTERNAL2://:39095
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:39092,EXTERNAL://172.31.47.65:39094,EXTERNAL2://fallrays.com:39095
      KAFKA_ADVERTISED_HOST_NAME: fallrays.com
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,EXTERNAL2:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      BOOTSTRAP_SERVERS: kafka-1:19092,kafka-2:29092,kafka-3:39092
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '2'
      KAFKA_NUM_PARTITIONS: '2'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
    volumes:
      - ./data/kafka-3/data:/var/lib/kafka/data
      - ./data/kafka-3/secrets:/etc/kafka/secrets

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "8099:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=fallrays-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:19092,kafka-2:29092,kafka-3:39092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181